# Generated by Django 4.2 on 2023-05-01 04:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_useraccount_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1000'), max_digits=10),
        ),
    ]
